Controllers/EquipmentController.cs
/*
 * @file    EquipmentController.cs
 * @name    ArtSchool - Equipment Loan System (Project for the IIS subject, FIT VUT)
 * @author  Marek Čupr (xcuprm01)
 * @brief   Controller for managing the equipment actions.
 */

using ArtSchool.Models;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using static System.Runtime.InteropServices.JavaScript.JSType;

namespace ArtSchool.Controllers
{
    public class EquipmentController : Controller
    {
        // Database context
        private readonly MyDBContext _context;

        public EquipmentController(MyDBContext context)
        {
            _context = context;
        }

        private async Task<Person> GetUserAsync()
        {
            // Get the user ID
            var userId = User.FindFirst("Id_user")?.Value;
            if (string.IsNullOrEmpty(userId) || !int.TryParse(userId, out int userIdInt))
            {
                return null;
            }

            // Retrieve the user from the database
            return await _context.Person.FirstOrDefaultAsync(u => u.Id_user == userIdInt);
        }

        private IActionResult RedirectToRolePage(Person user)
        {
            // Redirect the user based on his role
            return user.User_role switch
            {
                "admin" => RedirectToAction("Index", "AdminPage"),
                "atelier_manager" => RedirectToAction("Index", "AtelierManagerPage"),
                "teacher" => RedirectToAction("Index", "TeacherPage"),
                "user" => RedirectToAction("Index", "UserPage"),
                _ => RedirectToAction("Index", "LoginPage"),
            };
        }

        public async Task<IActionResult> Create()
        {
            // Get the current user from the database
            var user = await GetUserAsync();
            if (user == null)
            {
                TempData["error"] = "Přístup zamítnut, přihlaste se prosím.";
                return RedirectToAction("Index", "LoginPage");
            }

            // Retrieve the ateliers from the database
            List<Atelier> ateliers;
            if (user.User_role == "admin")
            {
                ateliers = await _context.Atelier.ToListAsync();
            }
            else
            {
                ateliers = await _context.AtelierPersons
                    .Where(ap => ap.Id_user == user.Id_user)
                    .Select(ap => ap.Atelier)
                    .ToListAsync();
            }

            // Retrieve the equipment types from the database
            var equipmentTypes = await _context.EquipmentType.ToListAsync();

            // Assign the corresponding ateliers and equipment types
            ViewData["Ateliers"] = ateliers;
            ViewData["EquipmentTypes"] = equipmentTypes;

            // Return the view
            return View();
        }

        [HttpPost]
        public async Task<IActionResult> Create(Equipment obj)
        {
            // Get the current user from the database
            var user = await GetUserAsync();
            if (user == null)
            {
                TempData["error"] = "Přístup zamítnut, přihlaste se prosím.";
                return RedirectToAction("Index", "LoginPage");
            }

            // Check if the manufacturing date is later than the purchase date
            if (obj.DateOfManufacture > obj.DateOfPurchase)
            {
                ModelState.AddModelError("DateOfManufacture", "Datum výroby nemůže být pozdější než datum nákupu.");
            }

            // Check if the manufacturing date is in the past
            if (obj.DateOfManufacture > DateTime.UtcNow)
            {
                ModelState.AddModelError("DateOfManufacture", "Datum výroby musí být v minulosti.");
            }

            // Check if the purchase date is in the past
            if (obj.DateOfPurchase > DateTime.UtcNow)
            {
                ModelState.AddModelError("DateOfPurchase", "Datum nákupu musí být v minulosti.");
            }

            // Retrieve the equipment type from the database
            var equipmentType = await _context.EquipmentType.FirstOrDefaultAsync(et => et.Id_type == obj.Id_type);
            if (equipmentType == null)
            {
                ModelState.AddModelError("Id_type", "Vybraný typ zařízení není platný.");
            }

            // Retrieve the atelier from the database
            var atelier = await _context.Atelier.FirstOrDefaultAsync(a => a.Id_atelier == obj.Id_atelier);
            if (atelier == null)
            {
                ModelState.AddModelError("Id_atelier", "Vybraný ateliér není platný.");
            }

            // Assign the corresponding atelier and equipment type
            obj.EquipmentType = equipmentType;
            obj.Atelier = atelier;

            // Don't validate the equipment type and atelier
            ModelState.Remove("EquipmentType");
            ModelState.Remove("Atelier");

            // Validate the input model
            if (!ModelState.IsValid)
            {
                // Retrieve the equipment types from the database
                var equipmentTypes = await _context.EquipmentType.ToListAsync();

                // Retrieve the ateliers from the database
                var ateliers = await _context.AtelierPersons
                    .Where(ap => ap.Id_user == user.Id_user)
                    .Select(ap => ap.Atelier)
                    .ToListAsync();

                // Store the ateliers and equipment types
                ViewData["Ateliers"] = ateliers;
                ViewData["EquipmentTypes"] = equipmentTypes;

                // Return the view with the equipment
                TempData["error"] = "Došlo k chybě při přidávání zařízení.";
                return View(obj);
            }

            // Try to add the equipment to the database
            try
            {
                _context.Equipment.Add(obj);
                await _context.SaveChangesAsync();
                TempData["success"] = "Zařízení bylo úspěšně přidáno.";
            }
            catch (Exception e)
            {
                TempData["error"] = "Došlo k chybě při přidávání zařízení. " + e;
            }

            // Redirect based on the user's role
            return RedirectToRolePage(user);
        }

        [HttpGet]
        public async Task<IActionResult> Edit(int id)
        {
            // Get the current user from the database
            var user = await GetUserAsync();
            if (user == null)
            {
                TempData["error"] = "Přístup zamítnut, přihlaste se prosím.";
                return RedirectToAction("Index", "LoginPage");
            }

            // Retrieve the equipment from the database
            var equipment = await _context.Equipment.FirstOrDefaultAsync(et => et.Id_equipment == id);
            if (equipment == null)
            {
                TempData["error"] = "Zařízení nenalezeno.";
                return RedirectToRolePage(user);
            }

            // Retrieve the ateliers from the database
            List<Atelier> ateliers;
            if (user.User_role == "admin")
            {
                ateliers = await _context.Atelier.ToListAsync();
            }
            else
            {
                ateliers = await _context.AtelierPersons
                      .Where(ap => ap.Id_user == user.Id_user && ap.Id_atelier != equipment.Id_atelier)
                      .Select(ap => ap.Atelier)
                      .ToListAsync();
            }
            
            // Retrieve the equipment types from the database
            var equipmentTypes = await _context.EquipmentType
                .Where(ap => ap.Id_type != equipment.Id_type)
                .ToListAsync();

            // Retrieve the atelier and equipment type from the database
            var atelier = await _context.Atelier.FirstOrDefaultAsync(ap => ap.Id_atelier == equipment.Id_atelier);
            var type = await _context.EquipmentType.FirstOrDefaultAsync(ap => ap.Id_type == equipment.Id_type);

            // Assign the corresponding ateliers and equipment types
            ViewData["Ateliers"] = ateliers;
            ViewData["EquipmentTypes"] = equipmentTypes;
            ViewData["Atelier"] = atelier;
            ViewData["Type"] = type;

            // Return the view with the equipment
            return View(equipment);
        }

        [HttpPost]
        public async Task<IActionResult> Edit(Equipment obj)
        {
            // Get the current user from the database
            var user = await GetUserAsync();
            if (user == null)
            {
                TempData["error"] = "Přístup zamítnut, přihlaste se prosím.";
                return RedirectToAction("Index", "LoginPage");
            }

            // Retrieve the equipment from the database
            var equipment = await _context.Equipment.FirstOrDefaultAsync(et => et.Id_equipment == obj.Id_equipment);
            if (equipment == null)
            {
                TempData["error"] = "Zařízení nenalezeno.";
                return RedirectToRolePage(user);
            }

            // Retrieve the equipment type from the database
            var equipmentType = await _context.EquipmentType.FirstOrDefaultAsync(et => et.Id_type == obj.Id_type);
            if (equipmentType == null)
            {
                ModelState.AddModelError("Id_type", "Vybraný typ zařízení není platný.");
            }

            // Retrieve the atelier from the database
            var atelier = await _context.Atelier.FirstOrDefaultAsync(a => a.Id_atelier == obj.Id_atelier);
            if (atelier == null)
            {

Controllers/LoanController.cs
/*
 * @file LoanController.cs
 * @name ArtSchool - Equipment Loan System (Project to subject IIS, FIT VUT)
 * @author Halva Jindřich (xhalva05)
 * @brief This file contains methods that operate with loans.
 */

using ArtSchool.Models;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;

namespace ArtSchool.Controllers
{
	public class LoanController : Controller
	{
		//get context from database
		private readonly MyDBContext _context;

		public LoanController(MyDBContext context)
		{
			_context = context;
		}

		public IActionResult Return(int id, string returnUrl)
		{
			//find loan by id
			var loan = _context.Loan.FirstOrDefault(l => l.Id_loan == id);

			try
			{
				//remove loan
				_context.Loan.Remove(loan);

				_context.SaveChanges();

				TempData["success"] = "Výpujčka byla úspěšně odstraněna.";
			}
			catch (Exception ex)
			{
				TempData["error"] = "Při odstraňování výpujčky došlo k chybě: " + ex;
			}

			return Redirect(returnUrl);
		}
	}
}

Controllers/TeacherPageController.cs
/*
 * @file TeacherPageController.cs
 * @name ArtSchool - Equipment Loan System (Project to subject IIS, FIT VUT)
 * @author Halva Jindřich (xhalva05)
 * @brief This file contains methods for the teacher page.
 */

using ArtSchool.Models;
using Microsoft.AspNetCore.Authentication;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using System.Diagnostics;

namespace ArtSchool.Controllers;

[Authorize(Roles = "teacher")]
public class TeacherPageController : Controller
{
	private readonly MyDBContext _context;

	public TeacherPageController(MyDBContext context)
	{
		_context = context;
	}

	public IActionResult Index()
    {
		var Id_user = User.FindFirst("Id_user")?.Value;

		if (Id_user == null)
		{
			return RedirectToAction("Index", "LoginPage");
		}

		//convert string id to int
		int Id_user_int = int.Parse(Id_user);

		//select teacher's ateliers
		var teacherAteliers = _context.AtelierPersons
							.Where(ap => ap.Id_user == Id_user_int)
							.Select(ap => ap.Id_atelier)
							.ToList();

		//list of equipments from ateliers, that user is in
		var equipmentList = _context.AtelierPersons
							 .Where(ap => ap.Id_user == Id_user_int)
							 .SelectMany(ap => ap.Atelier.Equipments)
							 .Include(et => et.EquipmentType)
							 .Include(a => a.Atelier)
							 .ToList();

		//list of user's loans
		var loanList = _context.Loan
							 .Where(l => l.Id_user == Id_user_int)
							 .Include(e => e.Equipment)
							 .ToList();

		//list of user's reservations
		var reservationList = _context.Reservation
							 .Where(r => r.Id_user == Id_user_int)
							 .Include(e => e.Equipment)
							 .ToList();

		//list of loans, that are from users, that are connected to at least one atelier same as the teacher
		var atelierLoansList = _context.Loan
							 .Where(l => l.Person.AtelierPersons.Any(ap => teacherAteliers.Contains(ap.Id_atelier)))
							 .Include(e => e.Equipment)
							 .Include(p => p.Person)
							 .ToList();

		//list of reservation requests, that are from users, that are connected to
		//at least one atelier same as the teacher
		var reservationRequestsList = _context.Reservation
								.Where(r => r.Person.AtelierPersons.Any(ap => teacherAteliers.Contains(ap.Id_atelier)))
								.Include(e => e.Equipment)
								.Include(p => p.Person)
								.ToList();

		//send lists with data by ViewData
		ViewData["Equipments"] = equipmentList;
		ViewData["Loans"] = loanList;
		ViewData["AtelierLoans"] = atelierLoansList;
		ViewData["Reservations"] = reservationList;
		ViewData["ReservationRequests"] = reservationRequestsList;

		return View();
	}
}

Views/TeacherPage/Index.cshtml
@{
    ViewData["Title"] = "Teacher Page";
    Layout = "_Layout";
}

<link rel="stylesheet" href="@Url.Content("~/css/site.css")" asp-append-version="true" />

<!--Show all equipment user can make reservation on-->
<div id="accordion" class="container">

	<div class="card mb-5">
		<button class="btn" data-toggle="collapse" data-target="#collapseRes" aria-expanded="true" aria-controls="collapseRes">
			<div class="card-header" id="ResRequestHeader">
				<h4 class="mb-0">
					Žádosti o rezervace
				</h4>
			</div>
		</button>
		<div id="collapseRes" class="collapse show" aria-labelledby="ResRequestHeader" data-parent="#accordion">
			<div class="card-body">
				<ul class="list-group" style="list-style:none;">
					<li class="list-group-item" style="background-color:aliceblue">
						<ul class="equip_unit_v2">
							<li><strong>id rez.</strong></li>
							<li><strong>příjmení</strong></li>
							<li><strong>zařízení</strong></li>
							<li><strong>začátek</strong></li>
							<li><strong>konec</strong></li>
							<li></li>
						</ul>
					</li>
					@foreach (var request in (IEnumerable<ArtSchool.Models.Reservation>)ViewData["ReservationRequests"])
					{
						<li class="list-group-item">
							<ul class="equip_unit_v2">
								<li><strong>@request.Id_reservation</strong></li>
								<li>@request.Person.Surname</li>
								<li>@request.Equipment.Name</li>
								<li>@request.DateOfReservation</li>
								<li>@request.DateOfEnd</li>
								<li>
									<form asp-controller="Reservation" asp-action="Accept" asp-route-id="@request.Id_reservation" method="post" class="d-inline">
										<button type="submit" class="edit btn p-2 m-1">
											<img src="~/images/check_icon.png" alt="Check" width="16" />
										</button>
									</form>
									<form method="post" asp-action="Delete" asp-controller="Reservation" asp-route-id="@request.Id_reservation" style="display: inline;">
										<button type="submit" class="delete btn p-2 m-1" onclick="return confirm('Opravdu chcete tuto rezervaci kompletně odebrat ze systému?')">
											<img src="~/images/tresh_icon.png" alt="Tresh" width="16" />
										</button>
									</form>
								</li>
							</ul>
						</li>
					}
				</ul>
			</div>
		</div>
	</div>

	<div class="card mb-5">
		<button class="btn" data-toggle="collapse" data-target="#collapseLoan" aria-expanded="true" aria-controls="collapseLoan">
			<div class="card-header" id="LoanHeader">
				<h4 class="mb-0">
					Výpujčky uživatelů
				</h4>
			</div>
		</button>
		<div id="collapseLoan" class="collapse show" aria-labelledby="LoanHeader" data-parent="#accordion">
			<div class="card-body">
				<ul class="list-group" style="list-style:none">
					<li class="list-group-item" style="background-color:aliceblue">
						<ul class="equip_unit_v2">
							<li><strong>id</strong></li>
							<li><strong>stav</strong></li>
							<li><strong>uživatel</strong></li>
							<li><strong>zařízení</strong></li>
							<li><strong>půjčení</strong></li>
							<li><strong>návrat</strong></li>
						</ul>
					</li>
					@foreach (var loan in (IEnumerable<ArtSchool.Models.Loan>)ViewData["AtelierLoans"])
					{
						<li class="list-group-item">
							<ul class="equip_unit_v2">
								<li><strong>@loan.Id_loan</strong></li>
								@if (loan.Status == "active")
								{
									<li style="color: aqua">AKTIVNÍ</li>
								}
								@if (loan.Status == "returned")
								{
									<li style="color: greenyellow">VRÁCENO</li>
								}
								@if (loan.Status == "overdue")
								{
									<li style="color: darkred">PO TERMÍNU</li>
								}
								<li>@loan.Person.Surname @loan.Person.Firstname</li>
								<li><strong>@loan.Equipment.Name</strong></li>
								<li>@loan.DateOfLoan</li>
								<li>
									@loan.DateOfReturn 
									<form method="post" asp-action="Return" asp-controller="Loan" style="display: inline;">
										<input type="hidden" name="id" value="@loan.Id_loan" />
										<input type="hidden" name="returnUrl" value="@Context.Request.Path" />
										<button type="submit" class="edit btn p-2 m-1"
												onclick="return confirm('Zařízení bylo navráceno? Tímto potvrdíte návrat a výpujčka bude ze systému vymazána.')">
											Navrácení
										</button>
									</form>
								</li>
							</ul>
						</li>
					}
				</ul>
			</div>
		</div>
	</div>

	<div class="card mb-5">
		<button class="btn" data-toggle="collapse" data-target="#collapseOne" aria-expanded="true" aria-controls="collapseOne">
			<div class="card-header" id="EquipHeader">
				<h4 class="mb-0">
					Zařízení
				</h4>
			</div>
		</button>
		<div id="collapseOne" class="collapse show" aria-labelledby="EquipHeader" data-parent="#accordion">
			<div>
				<a asp-controller="Equipment" asp-action="Create" class="add card-link btn my-1 mx-3 border">
					Přidat zařízení
				</a>
			</div>
			<div class="card-body">
				<ul class="list-group" style="list-style:none;">
					<li class="list-group-item" style="background-color:aliceblue">
						<ul class="equip_unit_v2">
							<li><strong>Název</strong></li>
							<li><strong>id</strong></li>
							<li><strong>typ</strong></li>
							<li><strong>atelier</strong></li>
							<li></li>
							<li></li>
						</ul>
					</li>
					@foreach (var equipment in (IEnumerable<ArtSchool.Models.Equipment>)ViewData["Equipments"])
					{
						<li class="list-group-item">
							<ul class="equip_unit_v2">
								<li><strong>@equipment.Name</strong></li>
								<li>@equipment.Id_equipment</li>
								<li>@equipment.EquipmentType.Name</li>
								<li>@equipment.Atelier.Name</li>
								<li><a asp-controller="Reservation" asp-action="Index" asp-route-id="@equipment.Id_equipment" class="edit btn p-2 m-1">Rezervace</a></li>
								<li>
									<a class="edit btn p-2 m-1" asp-action="Edit" asp-controller="Equipment" asp-route-id="@equipment.Id_equipment">
										<img src="~/images/edit_icon.png" alt="Edit" width="16"/>
									</a>
									<form method="post" asp-action="Delete" asp-controller="Equipment" asp-route-id="@equipment.Id_equipment" style="display: inline;">
										<button type="submit" class="rounded border-0 black_bg text-light p-2 m-1"
												onclick="return confirm('Opravdu chcete toto zařízení kompletně odstranit ze systému?')">
											<img src="~/images/tresh_icon.png" alt="Tresh" width="16" />
										</button>
									</form>
								</li>
							</ul>
						</li>
					}
				</ul>
			</div>
		</div>
	</div>

	<!--Show every user Loan-->
	<div class="card mb-5">
		<button class="btn" data-toggle="collapse" data-target="#collapseTwo" aria-expanded="true" aria-controls="collapseTwo">
			<div class="card-header" id="LoanHeader">
				<h4 class="mb-0">
					Výpujčky
				</h4>
			</div>
		</button>
		<div id="collapseTwo" class="collapse show" aria-labelledby="LoanHeader" data-parent="#accordion">
			<div class="card-body">
				<ul class="list-group" style="list-style:none">
					<li class="list-group-item" style="background-color:aliceblue">
						<ul class="equip_unit_v1">
							<li><strong>id</strong></li>
							<li><strong>stav</strong></li>
							<li><strong>zařízení</strong></li>
							<li><strong>půjčení</strong></li>
							<li><strong>návrat</strong></li>
						</ul>
					</li>
					@foreach (var loan in (IEnumerable<ArtSchool.Models.Loan>)ViewData["Loans"])
					{
						<li class="list-group-item">
							<ul class="equip_unit_v1">
								<li><strong>@loan.Id_loan</strong></li>
								@if (loan.Status == "active")
								{
									<li style="color: aqua">AKTIVNÍ</li>
								}
								@if (loan.Status == "returned")
								{
									<li style="color: greenyellow">VRÁCENO</li>
								}
								@if (loan.Status == "overdue")
								{
									<li style="color: darkred">PO TERMÍNU</li>
								}
								<li><strong>@loan.Equipment.Name</strong></li>
								<li>@loan.DateOfLoan</li>
								<li>@loan.DateOfReturn</li>
							</ul>
						</li>
					}
				</ul>
			</div>
		</div>
	</div>

	<!--Show reservation requests-->
	<div class="card mb-5">
		<button class="btn" data-toggle="collapse" data-target="#collapseThree" aria-expanded="true" aria-controls="collapseThree">
			<div class="card-header" id="ResHeader">
				<h4 class="mb-0">
					Rezervace
				</h4>
			</div>
		</button>
		<div id="collapseThree" class="collapse show" aria-labelledby="ResHeader" data-parent="#accordion">
			<div class="card-body">
				<ul class="list-group" style="list-style:none;">
					<li class="list-group-item" style="background-color:aliceblue">
						<ul class="equip_unit_v1">
							<li><strong>id</strong></li>
							<li><strong>zařízení</strong></li>
							<li><strong>začátek</strong></li>
							<li><strong>konec</strong></li>
							<li></li>
						</ul>
					</li>
					@foreach (var reservation in (IEnumerable<ArtSchool.Models.Reservation>)ViewData["Reservations"])
					{
						<li class="list-group-item">
							<ul class="equip_unit_v1">
								<li><strong>@reservation.Id_reservation</strong></li>
								<li><strong>@reservation.Equipment.Name</strong></li>
								<li>@reservation.DateOfReservation</li>
								<li>@reservation.DateOfEnd</li>
								<li>
									<form method="post" asp-action="Delete" asp-controller="Reservation" asp-route-id="@reservation.Id_reservation" style="display: inline;">
										<button type="submit" class="rounded border-0 black_bg text-light p-2 m-1" onclick="return confirm('Opravdu chcete tuto rezervaci kompletně odebrat ze systému?')">Odebrat</button>
									</form>
								</li>
							</ul>
						</li>
					}
				</ul>
			</div>
		</div>
	</div>
</div>