Controllers/AtelierManagerPageController.cs
/*
 * @file AtelierManagerPageController.cs
 * @name ArtSchool - Equipment Loan System (Project to subject IIS, FIT VUT)
 * @author Halva Jindřich (xhalva05)
 * @brief This file contains methods for AtelierManagerPage. 
 */

using ArtSchool.Models;
using Microsoft.AspNetCore.Authentication;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using System.Diagnostics;


namespace ArtSchool.Controllers;

[Authorize(Roles = "atelier_manager")]
public class AtelierManagerPageController : Controller
{
	private readonly MyDBContext _context;

	public AtelierManagerPageController(MyDBContext context)
	{
		_context = context;
	}

	public IActionResult Index()
	{
		var Id_user = User.FindFirst("Id_user")?.Value;

		if (Id_user == null)
		{
			return RedirectToAction("Index", "LoginPage");
		}

		//convert string id to int
		int Id_user_int = int.Parse(Id_user);

		//every manager is connected to one atelier so we can get it
		int Id_users_atelier = _context.AtelierPersons
						.Where(ap => ap.Id_user == Id_user_int)
						.Select(ap => ap.Id_atelier)
						.FirstOrDefault();

		//list of equipments from atelier, that manager is in
		var equipmentList = _context.AtelierPersons
							 .Where(ap => ap.Id_user == Id_user_int)
							 .SelectMany(ap => ap.Atelier.Equipments)
							 .Include(et => et.EquipmentType)
							 .Include(a => a.Atelier)
							 .ToList();

		//list of loans
		var loanList = _context.Loan
							 .Where(l => l.Id_user == Id_user_int)
							 .Include(e => e.Equipment)
							 .ToList();

		//list of reservations
		var reservationsList = _context.Reservation
							 .Where(r => r.Id_user == Id_user_int)
							 .Include(e => e.Equipment)
							 .ToList();

		//get users that are connected to atelier of the manager
		var userslist = _context.AtelierPersons
						.Where(ap => ap.Id_atelier == Id_users_atelier)
						.Include(p => p.Person)
						.ToList();

		var managers_atelierList = _context.Atelier
						.Where(a => a.Id_atelier == Id_users_atelier)
						.ToList();		

		var typesList = _context.EquipmentType
						.ToList();

		//send lists with data by ViewData
		ViewData["Equipments"] = equipmentList;
		ViewData["Loans"] = loanList;
		ViewData["Reservations"] = reservationsList;
		ViewData["Users"] = userslist;
		ViewData["Types"] = typesList;
		ViewData["Atelier"] = managers_atelierList;
		ViewData["AtelierName"] = _context.Atelier
								.Where(a => a.Id_atelier == Id_users_atelier)
								.Select(a => a.Name)
								.FirstOrDefault();
		ViewData["AtelierId"] = Id_users_atelier;

		return View();
	}
}


Controllers/ReservationController.cs
/*
 * @file    ReservationController.cs
 * @name    ArtSchool - Equipment Loan System (Project for the IIS subject, FIT VUT)
 * @author  Marek Čupr (xcuprm01)
 * @brief   Controller for managing the reservation actions.
 */

using ArtSchool.Models;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using Microsoft.Extensions.Logging;

namespace ArtSchool.Controllers
{
    public class ReservationController : Controller
    {
        // Database context
        private readonly MyDBContext _context;

        public ReservationController(MyDBContext context)
        {
            _context = context;
        }

        private async Task<Person> GetUserAsync()
        {
            // Get the user ID
            var userId = User.FindFirst("Id_user")?.Value;
            if (string.IsNullOrEmpty(userId) || !int.TryParse(userId, out int userIdInt))
            {
                return null;
            }

            // Retrieve the user from the database
            return await _context.Person.FirstOrDefaultAsync(u => u.Id_user == userIdInt);
        }

        private IActionResult RedirectToRolePage(Person user)
        {
            // Redirect the user based on his role
            return user.User_role switch
            {
                "admin" => RedirectToAction("Index", "AdminPage"),
                "atelier_manager" => RedirectToAction("Index", "AtelierManagerPage"),
                "teacher" => RedirectToAction("Index", "TeacherPage"),
                "user" => RedirectToAction("Index", "UserPage"),
                _ => RedirectToAction("Index", "LoginPage"),
            };
        }

        public async Task<IActionResult> Index(int id)
        {
            // Get the current user from the database
            var user = await GetUserAsync();
            if (user == null)
            {
                TempData["error"] = "Přístup zamítnut, přihlaste se prosím.";
                return RedirectToAction("Index", "LoginPage");
            }

            // Retrieve the equipment from the database
            var equipment = await _context.Equipment.FirstOrDefaultAsync(e => e.Id_equipment == id);
            if (equipment == null)
            {
                TempData["error"] = "Zařízení nenalezeno.";
                return RedirectToRolePage(user);
            }

            // Assign the corresponding equipment and id
            ViewData["Equipment"] = equipment;
            ViewData["Id"] = id;

            // Return the view
            return View();
        }

        [HttpGet]
        public IActionResult GetReservations(int id)
        {
            // Retrieve the reservations from the database
            var reservations = _context.Reservation
                .Where(r => r.Id_equipment == id)
                .Include(r => r.Equipment)
                .Include(r => r.Person)
                .ToList();

            // Create reservation events for the calendar
            var reservationEvents = reservations.Select(r => new
            {
                type = "reservation",
                title = $"Rezervace zařízení {r.Equipment.Name} - {r.Person.Firstname} {r.Person.Surname}",
                start = r.DateOfReservation.ToString("yyyy-MM-ddTHH:mm:ss"),
                end = r.DateOfEnd.ToString("yyyy-MM-ddTHH:mm:ss")
            }).ToList();

            // Retrieve the loans from the database
            var loans = _context.Loan
                .Where(l => l.Id_equipment == id)
                .Include(l => l.Equipment)
                .Include(l => l.Person)
                .ToList();

            // Create loan events for the calendar
            var loanEvents = loans.Select(l => new
            {
                type = "loan",
                title = $"Výpůjčka zařízení {l.Equipment.Name} - {l.Person.Firstname} {l.Person.Surname}",
                start = l.DateOfLoan.ToString("yyyy-MM-ddTHH:mm:ss"),
                end = l.DateOfReturn.ToString("yyyy-MM-ddTHH:mm:ss")
            }).ToList();

            // Combine the reservations and loans
            var allEvents = reservationEvents.Concat(loanEvents).ToList();

            // Return the calendar events as JSON
            return Json(allEvents);
        }

        [HttpPost]
        public async Task<IActionResult> AddReservation(Reservation obj)
        {
            // Get the user ID
            var userId = User.FindFirst("Id_user")?.Value;

            // Check if the user ID is valid
            if (string.IsNullOrEmpty(userId) || !int.TryParse(userId, out int userIdInt))
            {
                return RedirectToAction("Index", "LoginPage");
            }

            // Retrieve the user from the database
            var user = await _context.Person.FirstOrDefaultAsync(u => u.Id_user == userIdInt);

            // Check if the user was found
            if (user == null)
            {
                return RedirectToAction("Index", "LoginPage");
            }

            // Retrieve the equipment from the database
            var equipment = await _context.Equipment.FirstOrDefaultAsync(et => et.Id_equipment == obj.Id_equipment);
            if (equipment == null)
            {
                TempData["error"] = "Zařízení nenalezeno.";
                return RedirectToRolePage(user);
            }

            // Check for overlapping reservations for the same equipment
            var existingReservation = await _context.Reservation
                .FirstOrDefaultAsync(r =>
                    r.Id_equipment == obj.Id_equipment &&
                    ((obj.DateOfReservation >= r.DateOfReservation && obj.DateOfReservation < r.DateOfEnd) ||
                     (obj.DateOfEnd > r.DateOfReservation && obj.DateOfEnd <= r.DateOfEnd))
                );

            // Check if overlapping reservation already exists
            if (existingReservation != null)
            {
                TempData["error"] = "Pro zařízení již existuje rezervace v této době.";
                return RedirectToAction("Index", new { id = obj.Id_equipment });
            }

            // Check for overlapping loans for the same equipment
            var existingLoans = await _context.Loan
                .FirstOrDefaultAsync(r =>
                    r.Id_equipment == obj.Id_equipment &&
                    ((obj.DateOfReservation >= r.DateOfLoan && obj.DateOfReservation < r.DateOfReturn) ||
                     (obj.DateOfEnd > r.DateOfLoan && obj.DateOfEnd <= r.DateOfReturn))
                );

            // Check if overlapping loan already exists
            if (existingLoans != null)
            {
                TempData["error"] = "Pro zařízení již existuje výpůjčka v této době.";
                return RedirectToAction("Index", new { id = obj.Id_equipment });
            }

            // Check if the reservation date is not in the past
            if (obj.DateOfReservation < DateTime.UtcNow)
            {
                TempData["error"] = "Rezervace nesmí být v minulosti.";
                return RedirectToAction("Index", new { id = obj.Id_equipment });
            }

            // Check if the loan durations isn't greater than the maximum equipment loan allowd
            TimeSpan difference = obj.DateOfEnd - obj.DateOfReservation;
            int daysDifference = difference.Days;
            if (daysDifference > equipment.MaxLoanDuration) 
            {
                TempData["error"] = $"Doba výpůjčky nesmí být delší než maximálně povlená doba: {equipment.MaxLoanDuration} dní.";
                return RedirectToAction("Index", new { id = obj.Id_equipment });
            }

            // Don't validate the person and equipment
            ModelState.Remove("Person");
            ModelState.Remove("Equipment");

            // Validate the input model
            if (ModelState.IsValid)
            {
                // Create a new reservation instance
                var reservation = new Reservation
                {
                    DateOfReservation = obj.DateOfReservation,
                    DateOfEnd = obj.DateOfEnd,
                    Id_equipment = obj.Id_equipment,
                    Id_user = userIdInt,
                    Person = user,
                    Equipment = equipment
                };

                // Add the reservation to the database
                _context.Reservation.Add(reservation);
                await _context.SaveChangesAsync();
                TempData["success"] = "Rezervace byla úspěšně přidána.";
            }
            else
            {
                TempData["error"] = "Došlo k chybě při přidávání rezervace.";
            }

            // Redirect back to the calendar
            return RedirectToAction("Index", new { id = obj.Id_equipment });
        }

        [HttpPost]
        public async Task<IActionResult> Accept(int id)
        {
            // Get the current user from the database
            var user = await GetUserAsync();
            if (user == null)
            {
                TempData["error"] = "Přístup zamítnut, přihlaste se prosím.";
                return RedirectToAction("Index", "LoginPage");
            }

            // Retrieve the reservation from the database
            var reservation = await _context.Reservation
                    .Include(r => r.Equipment)
                    .Include(r => r.Person)
                    .FirstOrDefaultAsync(r => r.Id_reservation == id);

            // Check if the reservation was found
            if (reservation == null)
            {
                TempData["error"] = "Rezervace nebyla nenalezena.";
                return RedirectToRolePage(user);
            }

            // Create a new loan instance

Controllers/TypeController.cs
/*
 * @file TypeController.cs
 * @name ArtSchool - Equipment Loan System (Project to subject IIS, FIT VUT)
 * @author Halva Jindřich (xhalva05)
 * @brief This file contains methods that operate equipment types.
 */

using ArtSchool.Models;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Authorization.Infrastructure;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using System.Drawing.Drawing2D;

namespace ArtSchool.Controllers
{
	[Authorize(Roles = "atelier_manager, admin")]
	public class TypeController : Controller
	{

		private readonly MyDBContext _context;

		public TypeController(MyDBContext context)
		{
			_context = context;
		}

		// GET: Type/Create
		[HttpGet]
		public ActionResult Create(string returnUrl)
		{
			ViewData["ReturnUrl"] = returnUrl;
			return View();
		}

		//create new type
		[HttpPost]
		[ValidateAntiForgeryToken]
		public ActionResult Create(EquipmentType new_type, string returnUrl)
		{
			if (ModelState.IsValid) {
				try
				{
					//add new type to database
					_context.EquipmentType.Add(new_type);
					_context.SaveChanges();
                    TempData["success"] = "Nový typ zařízení úspěšně přidán.";
                    return Redirect(returnUrl);
				}
				catch
				{
                    TempData["Error"] = "Vyskytla se chyba při vytváření ateliéru.";
                }
			}
			ViewData["ReturnUrl"] = returnUrl;
			return View(new_type);
		}

		[HttpGet]
		public ActionResult Edit(int id, string returnUrl)
		{
			//find type by id
			var type = _context.EquipmentType.FirstOrDefault(t => t.Id_type == id);
			//if type was not found
			if (type == null)
            {
				ModelState.AddModelError("", "Došlo k chybě při úpravě typu zařízení.");
                ViewData["ReturnUrl"] = returnUrl;
                return View();
            }

            ViewData["ReturnUrl"] = returnUrl;
            return View(type);
        }

		//edit type 
		[HttpPost]
		[ValidateAntiForgeryToken]
		public ActionResult Edit(int id, EquipmentType edited_type, string returnUrl)
		{
            if (ModelState.IsValid)
            {
                try
                {
                    _context.EquipmentType.Update(edited_type);
                    _context.SaveChanges();
                    TempData["success"] = "Typ zařízení byl úspěšně upraven.";
                    return Redirect(returnUrl);
                }
                catch
                {
                    TempData["Error"] = "Vyskytla se chyba při úpravě ateliéru.";
                }
            }
            ViewData["ReturnUrl"] = returnUrl;
            return View(edited_type);
        }

		[HttpPost]
		[ValidateAntiForgeryToken]
		public ActionResult Delete(int id, string returnUrl)
		{
			//find type include equipments of this type
			var equipmentType = _context.EquipmentType
				   .Include(et => et.Equipments)
				   .FirstOrDefault(et => et.Id_type == id);

			try
			{
				//delete all equipments of this type
				foreach (var equipment in equipmentType.Equipments)
				{
					_context.Equipment.Remove(equipment);
				}

				//remove type
				_context.EquipmentType.Remove(equipmentType);

				_context.SaveChanges();

				TempData["success"] = "Typ zařízení byl úspěšně odstraněn.";
			}
			catch (Exception ex)
			{
				TempData["error"] = "Při odstraňování typu zařízení došlo k chybě: " + ex;
			}

			return Redirect(returnUrl);
		}
	}
}

Views/AtelierManagerPage/Index.cshtml
@{
    ViewData["Title"] = "Manager Page";
    Layout = "_Layout";
}


<link rel="stylesheet" href="@Url.Content("~/css/site.css")" asp-append-version="true" />

<!--Show all equipment user can make reservation on-->
<div id="accordion" class="container">

	<!--Show users connected to the manager's atelier-->
	<div class="card mb-5">
		<button class="btn" data-toggle="collapse" data-target="#collapseOne" aria-expanded="true" aria-controls="collapseOne">
			<div class="card-header" id="AtelierUsersHeader">
				<h4 class="mb-0">

					Uživatelé ateliéru <b>@ViewData["AtelierName"]</b>
				</h4>
			</div>
		</button>
		<div id="collapseOne" class="collapse show" aria-labelledby="AtelierUsersHeader" data-parent="#accordion">
			<div>
				<a asp-controller="AtelierUsers" asp-action="Index" asp-route-atelier_id="@ViewData["AtelierId"]"
				   asp-route-returnUrl="@Context.Request.Path" class="add card-link btn my-1 mx-3 border">
					Přidat uživatele
				</a>
			</div>
			<div class="card-body">
				<ul class="list-group" style="list-style:none">
					<li class="list-group-item" style="background-color:aliceblue">
						<ul class="equip_unit_v1">
							<li><strong>id</strong></li>
							<li><strong>Jméno</strong></li>
							<li><strong>Příjmení</strong></li>
							<li><strong>Role</strong></li>
							<li><strong></strong></li>
						</ul>
					</li>
					@foreach (var user in (IEnumerable<ArtSchool.Models.AtelierPersons>)ViewData["Users"])
					{
						@if (user.Person.User_role != "atelier_manager")
						{
						<li class="list-group-item">
							<ul class="equip_unit_v1">
								<li><strong>@user.Person.Id_user</strong></li>
								<li><strong>@user.Person.Firstname</strong></li>
								<li>@user.Person.Surname</li>
								@if(user.Person.User_role == "user")
								{
									<li>student</li>
								}
								@if(user.Person.User_role == "teacher")
								{
									<li>učitel</li>
								}
								<li>
									<a asp-controller="AtelierUsers" asp-action="Edit" asp-route-Id_User="@user.Id_user"
									   asp-route-returnUrl="@Context.Request.Path" class="edit btn p-2 m-1">
										<img src="~/images/edit_icon.png" alt="Edit" width="16" />
									</a>
									<form method="post" asp-action="Delete" asp-controller="AtelierUsers" style="display: inline;">
										<input type="hidden" name="Id_User" value="@user.Id_user" />
										<input type="hidden" name="returnUrl" value="@Context.Request.Path" />
										<button type="submit" class="delete btn p-2 m-1"
												onclick="return confirm('Opravdu chcete tohoto uživatele odstranit z ateliéru? Tato akce je nevratná a vymažete tím i případné rezervace daného uživatele v tomto ateliéru.')">
											<img src="~/images/tresh_icon.png" alt="Tresh" width="16" />
										</button>
									</form>
								</li>
							</ul>
						</li>
						}
					}
				</ul>
			</div>
		</div>
	</div>

	<div class="card mb-5">
		<button class="btn" data-toggle="collapse" data-target="#collapseTwo" aria-expanded="true" aria-controls="collapseTwo">
			<div class="card-header" id="EquipTypeHeader">
				<h4 class="mb-0">
					Typy zařízení
				</h4>
			</div>
		</button>
		<div id="collapseTwo" class="collapse show" aria-labelledby="EquipTypeHeader" data-parent="#accordion">
			<div>
				<a asp-controller="Type" asp-action="Create" asp-route-returnUrl="@Context.Request.Path" class="add btn my-1 mx-3 border">
					Přidat nový typ
				</a>
			</div>
			<div class="card-body">
				<ul class="list-group" style="list-style:none;">
					<li class="list-group-item" style="background-color:aliceblue">
						<ul class="equip_unit_v3">
							<li><strong>id</strong></li>
							<li><strong>Název</strong></li>
							<li></li>
						</ul>
					</li>
					@foreach (var type in (IEnumerable<ArtSchool.Models.EquipmentType>)ViewData["Types"])
					{
						<li class="list-group-item">
							<ul class="equip_unit_v3">
								<li><strong>@type.Id_type</strong></li>
								<li>@type.Name</li>
								<li>
									<a asp-controller="Type" asp-action="Edit" asp-route-id="@type.Id_type"
									   asp-route-returnUrl="@Context.Request.Path" class="edit btn p-2 m-1">
										<img src="~/images/edit_icon.png" alt="Edit" width="16" />
									</a>
									<form method="post" asp-action="Delete" asp-controller="Type" style="display: inline;">
										<input type="hidden" name="id" value="@type.Id_type" />
										<input type="hidden" name="returnUrl" value="@Context.Request.Path" />
										<button type="submit" class="delete btn p-2 m-1" 
												onclick="return confirm('Opravdu chcete tento typ zařízení smazat? Tato akce je nevratná a vymažete tím i případné zažízení daného typu.')">
											<img src="~/images/tresh_icon.png" alt="Tresh" width="16" />
										</button>
									</form>
								</li>
							</ul>
						</li>
					}
				</ul>
			</div>
		</div>
	</div>

	<div class="card mb-5">
		<button class="btn" data-toggle="collapse" data-target="#collapseThree" aria-expanded="true" aria-controls="collapseThree">
			<div class="card-header" id="EquipHeader">
				<h4 class="mb-0">
					Zařízení
				</h4>
			</div>
		</button>
		<div id="collapseThree" class="collapse show" aria-labelledby="EquipHeader" data-parent="#accordion">
			<div class="card-body">
				<ul class="list-group" style="list-style:none;">
					<li class="list-group-item" style="background-color:aliceblue">
						<ul class="equip_unit_v1">
							<li><strong>Název</strong></li>
							<li><strong>id</strong></li>
							<li><strong>typ</strong></li>
							<li><strong>atelier</strong></li>
							<li></li>
						</ul>
					</li>
					@foreach (var equipment in (IEnumerable<ArtSchool.Models.Equipment>)ViewData["Equipments"])
					{
						<li class="list-group-item">
							<ul class="equip_unit_v1">
								<li><strong>@equipment.Name</strong></li>
								<li>@equipment.Id_equipment</li>
								<li>@equipment.EquipmentType.Name</li>
								<li>@equipment.Atelier.Name</li>
								<li><a asp-controller="Reservation" asp-action="Index" asp-route-id="@equipment.Id_equipment" class="edit btn p-2 m-1">Rezervace</a></li>
							</ul>
						</li>
					}
				</ul>
			</div>
		</div>
	</div>

	<!--Show every user Loan-->
	<div class="card mb-5">
		<button class="btn" data-toggle="collapse" data-target="#collapseFour" aria-expanded="true" aria-controls="collapseFour">
			<div class="card-header" id="LoanHeader">
				<h4 class="mb-0">
					Výpujčky
				</h4>
			</div>
		</button>
		<div id="collapseFour" class="collapse show" aria-labelledby="LoanHeader" data-parent="#accordion">
			<div class="card-body">
				<ul class="list-group" style="list-style:none">
					<li class="list-group-item" style="background-color:aliceblue">
						<ul class="equip_unit_v1">
							<li><strong>id</strong></li>
							<li><strong>stav</strong></li>
							<li><strong>zařízení</strong></li>
							<li><strong>půjčení</strong></li>
							<li><strong>návrat</strong></li>
						</ul>
					</li>
					@foreach (var loan in (IEnumerable<ArtSchool.Models.Loan>)ViewData["Loans"])
					{
						<li class="list-group-item">
							<ul class="equip_unit_v1">
								<li><strong>@loan.Id_loan</strong></li>
								@if (loan.Status == "active")
								{
									<li style="color: aqua">AKTIVNÍ</li>
								}
								@if (loan.Status == "returned")
								{
									<li style="color: greenyellow">VRÁCENO</li>
								}
								@if (loan.Status == "overdue")
								{
									<li style="color: darkred">PO TERMÍNU</li>
								}
								<li><strong>@loan.Equipment.Name</strong></li>
								<li>@loan.DateOfLoan</li>
								<li>@loan.DateOfReturn</li>
							</ul>
						</li>
					}
				</ul>
			</div>
		</div>
	</div>

	<!--Show reservation requests-->
	<div class="card mb-5">
		<button class="btn" data-toggle="collapse" data-target="#collapseFive" aria-expanded="true" aria-controls="collapseFive">
			<div class="card-header" id="ResHeader">
				<h4 class="mb-0">
					Rezervace
				</h4>
			</div>
		</button>
		<div id="collapseFive" class="collapse show" aria-labelledby="ResHeader" data-parent="#accordion">
			<div class="card-body">
				<ul class="list-group" style="list-style:none;">
					<li class="list-group-item" style="background-color:aliceblue">
						<ul class="equip_unit_v1">
							<li><strong>id</strong></li>
							<li><strong>zařízení</strong></li>
							<li><strong>začátek</strong></li>
							<li><strong>konec</strong></li>
							<li></li>
						</ul>
					</li>
					@foreach (var reservation in (IEnumerable<ArtSchool.Models.Reservation>)ViewData["Reservations"])
					{
						<li class="list-group-item">
							<ul class="equip_unit_v1">
								<li><strong>@reservation.Id_reservation</strong></li>
								<li><strong>@reservation.Equipment.Name</strong></li>
								<li>@reservation.DateOfReservation</li>
								<li>@reservation.DateOfEnd</li>
								<li>
									<form method="post" asp-action="Delete" asp-controller="Reservation" asp-route-id="@reservation.Id_reservation" style="display: inline;">
										<button type="submit" class="delete btn p-2 m-1" onclick="return confirm('Opravdu chcete tuto rezervaci kompletně odebrat ze systému?')">
											<img src="~/images/tresh_icon.png" alt="Tresh" width="16" />
										</button>
									</form>
								</li>
							</ul>
						</li>
					}
				</ul>
			</div>
		</div>
	</div>
</div>